/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Consumption;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-03T16:56:55.966Z")

@Api(value = "consumption", description = "the consumption API")
public interface ConsumptionApi {

    @ApiOperation(value = "", nickname = "getConsumption", notes = "Get the Consumption for Given MeterID and Month", response = Consumption.class, tags={ "consumption", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Consumption.class),
        @ApiResponse(code = 400, message = "Invalid Month"),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/consumption/{meterID}/{month}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Consumption> getConsumption(@ApiParam(value = "Unique ID of the Meter", required = true) @PathVariable("meterID") String meterID, @ApiParam(value = "Month of the Year", required = true, allowableValues = "JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC") @PathVariable("month") String month);

}
