/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Fraction;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-03T16:56:55.966Z")

@Api(value = "fraction", description = "the fraction API")
public interface FractionApi {

    @ApiOperation(value = "", nickname = "createFraction", notes = "Add the fraction for Given Profile and Month", response = Fraction.class, tags={ "fraction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Fraction.class),
        @ApiResponse(code = 400, message = "Invalid Month or Fraction"),
        @ApiResponse(code = 404, message = "Profile Not Found") })
    @RequestMapping(value = "/fraction/{profile}/{month}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Fraction> createFraction(@ApiParam(value = "Profile Id", required = true) @PathVariable("profile") String profile, @ApiParam(value = "Month of the Year", required = true, allowableValues = "JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC") @PathVariable("month") String month, @NotNull @ApiParam(value = "Distribution of the Consumption among months in a year. Maximum possible value is 1.", required = true) @Valid @RequestParam(value = "fraction", required = true) Float fraction);


    @ApiOperation(value = "", nickname = "deleteFraction", notes = "Delete the fraction for Given Profile and Month", tags={ "fraction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Invalid Month"),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/fraction/{profile}/{month}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteFraction(@ApiParam(value = "Profile Id", required = true) @PathVariable("profile") String profile, @ApiParam(value = "Month of the Year", required = true, allowableValues = "JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC") @PathVariable("month") String month);


    @ApiOperation(value = "", nickname = "getFraction", notes = "Get the fraction for Given Profile and Month", response = Fraction.class, tags={ "fraction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Fraction.class),
        @ApiResponse(code = 400, message = "Invalid Profile OR Month"),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/fraction/{profile}/{month}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Fraction> getFraction(@ApiParam(value = "Profile Id", required = true) @PathVariable("profile") String profile, @ApiParam(value = "Month of the Year", required = true, allowableValues = "JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC") @PathVariable("month") String month);


    @ApiOperation(value = "", nickname = "updateFraction", notes = "Update the fraction for Given Profile and Month", response = Fraction.class, tags={ "fraction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Fraction.class),
        @ApiResponse(code = 400, message = "Invalid Profile OR Month"),
        @ApiResponse(code = 404, message = "NOT FOUND") })
    @RequestMapping(value = "/fraction/{profile}/{month}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Fraction> updateFraction(@ApiParam(value = "Profile Id", required = true) @PathVariable("profile") String profile, @ApiParam(value = "Month of the Year", required = true, allowableValues = "JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC") @PathVariable("month") String month, @NotNull @ApiParam(value = "Distribution of the Consumption among months in a year. Maximum possible value is 1.", required = true) @Valid @RequestParam(value = "fraction", required = true) Float fraction);

}
